spring:
  datasource:
    url: jdbc:h2:mem:dev
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none # Don't create the entities on start up
  h2:
    console:
      enabled: true # http://localhost:8080/h2
      path: /h2
      settings:
        trace: false
        web-allow-others: false
  flyway:
    user: sa
    password:
    url: jdbc:h2:mem:dev

