spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev
    driver-class-name: org.postgresql.Driver
    username: root
    password: toor
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
  flyway:
    url: jdbc:postgresql://localhost:5432/dev
    user: root
    password: toor
